spring.application.name=adms

spring.datasource.url=jdbc:postgresql://localhost:5432/adms
spring.datasource.username=adms
spring.datasource.password=adms_password

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true